# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'bilibili_imitate' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'RDVTabBarController'

  # Pods for bilibili_imitate

end
